package entity;
// Generated 01/07/2020 11:16:41 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "bookstoredb")
@NamedQueries({
	@NamedQuery(name = "Category.findAll", query = "select c from Category c"),
	@NamedQuery(name = "Category.count", query = "SELECT COUNT(c.nameCategory) FROM Category c "),
	@NamedQuery(name = "Category.findByName", query = "select c from Category c where c.nameCategory = :name")
})
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer categoryId;
	private String nameCategory;
	private Set<Book> books = new HashSet<Book>(0);

	public Category() {
	}

	public Category(String nameCategory, Set<Book> books) {
		this.nameCategory = nameCategory;
		this.books = books;
	}
	
	public Category(Integer categoryid, String nameCategory, Set<Book> books) {
		this.nameCategory = nameCategory;
		this.books = books;
		this.categoryId = categoryid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "name", length = 150)
	public String getNameCategory() {
		return this.nameCategory;
	}

	public void setNameCategory(String nameCategory) {
		this.nameCategory = nameCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
